In [45]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.0.3'

In [11]:
!pip install wget

  Using cached wget-3.2-py3-none-any.whl


In [12]:
import wget

In [14]:
wget.download('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv','housing.csv')

'housing.csv'

In [36]:
df = pd.read_csv('housing.csv')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [18]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [20]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [21]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [37]:
df.total_bedrooms.mean()

537.8705525375618

In [40]:
df.total_bedrooms.isnull().sum()

0

In [39]:
df['total_bedrooms'] = df.total_bedrooms.fillna(537.8705525375618)

In [41]:
df.total_bedrooms.mean()

537.8705525375617

In [80]:
X = df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [81]:
X

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [82]:
X = np.array(X)

In [83]:
XTX = np.transpose(X).dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [84]:
y = [950, 1300, 800, 1000, 1300]

In [85]:
XTX_inv = np.linalg.inv(XTX)

In [86]:
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [87]:
XTX_inv.dot(XTX)

array([[ 1.00000000e+00,  4.64341239e-13,  1.18269543e-13],
       [-4.39833716e-16,  1.00000000e+00, -1.66300350e-15],
       [ 1.04674299e-15,  1.09601998e-14,  1.00000000e+00]])

In [88]:
w = XTX_inv.dot(np.transpose(X))

In [89]:
w

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [90]:
w = w.dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])